// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/open-farms/inventory/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
