// Code generated by entc, DO NOT EDIT.

package http

import (
	"time"
)

// Payload of a ent.Category create request.
type CategoryCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Vehicle    []int      `json:"vehicle"`
	Tool       []int      `json:"tool"`
	Implement  []int      `json:"implement"`
	Equipment  []int      `json:"equipment"`
	Location   []int      `json:"location"`
}

// Payload of a ent.Category update request.
type CategoryUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Vehicle    []int      `json:"vehicle"`
	Tool       []int      `json:"tool"`
	Implement  []int      `json:"implement"`
	Equipment  []int      `json:"equipment"`
	Location   []int      `json:"location"`
}

// Payload of a ent.Equipment create request.
type EquipmentCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Condition  *string    `json:"condition"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Equipment update request.
type EquipmentUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Condition  *string    `json:"condition"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Implement create request.
type ImplementCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Implement update request.
type ImplementUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Location create request.
type LocationCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Zone       *int32     `json:"zone"`
	Vehicle    []int      `json:"vehicle"`
	Tool       []int      `json:"tool"`
	Implement  []int      `json:"implement"`
	Equipment  []int      `json:"equipment"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Location update request.
type LocationUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Zone       *int32     `json:"zone"`
	Vehicle    []int      `json:"vehicle"`
	Tool       []int      `json:"tool"`
	Implement  []int      `json:"implement"`
	Equipment  []int      `json:"equipment"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Tool create request.
type ToolCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Powered    *bool      `json:"powered"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Tool update request.
type ToolUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Name       *string    `json:"name"`
	Powered    *bool      `json:"powered"`
	Location   *int       `json:"location"`
	Category   *int       `json:"category"`
}

// Payload of a ent.Vehicle create request.
type VehicleCreateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Make       *string    `json:"make"`
	Model      *string    `json:"model"`
	Hours      *int64     `json:"hours"`
	Year       *int64     `json:"year"`
	Active     *bool      `json:"active"`
	Power      *string    `json:"power"`
	Location   *int       `json:"location"`
}

// Payload of a ent.Vehicle update request.
type VehicleUpdateRequest struct {
	CreateTime *time.Time `json:"create_time"`
	UpdateTime *time.Time `json:"update_time"`
	Make       *string    `json:"make"`
	Model      *string    `json:"model"`
	Hours      *int64     `json:"hours"`
	Year       *int64     `json:"year"`
	Active     *bool      `json:"active"`
	Power      *string    `json:"power"`
	Location   *int       `json:"location"`
}
