// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/open-farms/inventory/ent/category"
)

// Category is the model entity for the Category schema.
type Category struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CategoryQuery when eager-loading is set.
	Edges CategoryEdges `json:"edges"`
}

// CategoryEdges holds the relations/edges for other nodes in the graph.
type CategoryEdges struct {
	// Vehicle holds the value of the vehicle edge.
	Vehicle []*Vehicle `json:"vehicle,omitempty"`
	// Tool holds the value of the tool edge.
	Tool []*Tool `json:"tool,omitempty"`
	// Implement holds the value of the implement edge.
	Implement []*Implement `json:"implement,omitempty"`
	// Equipment holds the value of the equipment edge.
	Equipment []*Equipment `json:"equipment,omitempty"`
	// Location holds the value of the location edge.
	Location []*Location `json:"location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// VehicleOrErr returns the Vehicle value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) VehicleOrErr() ([]*Vehicle, error) {
	if e.loadedTypes[0] {
		return e.Vehicle, nil
	}
	return nil, &NotLoadedError{edge: "vehicle"}
}

// ToolOrErr returns the Tool value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) ToolOrErr() ([]*Tool, error) {
	if e.loadedTypes[1] {
		return e.Tool, nil
	}
	return nil, &NotLoadedError{edge: "tool"}
}

// ImplementOrErr returns the Implement value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) ImplementOrErr() ([]*Implement, error) {
	if e.loadedTypes[2] {
		return e.Implement, nil
	}
	return nil, &NotLoadedError{edge: "implement"}
}

// EquipmentOrErr returns the Equipment value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) EquipmentOrErr() ([]*Equipment, error) {
	if e.loadedTypes[3] {
		return e.Equipment, nil
	}
	return nil, &NotLoadedError{edge: "equipment"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading.
func (e CategoryEdges) LocationOrErr() ([]*Location, error) {
	if e.loadedTypes[4] {
		return e.Location, nil
	}
	return nil, &NotLoadedError{edge: "location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Category) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case category.FieldID:
			values[i] = new(sql.NullInt64)
		case category.FieldName:
			values[i] = new(sql.NullString)
		case category.FieldCreateTime, category.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Category", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Category fields.
func (c *Category) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case category.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case category.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				c.CreateTime = value.Time
			}
		case category.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				c.UpdateTime = value.Time
			}
		case category.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		}
	}
	return nil
}

// QueryVehicle queries the "vehicle" edge of the Category entity.
func (c *Category) QueryVehicle() *VehicleQuery {
	return (&CategoryClient{config: c.config}).QueryVehicle(c)
}

// QueryTool queries the "tool" edge of the Category entity.
func (c *Category) QueryTool() *ToolQuery {
	return (&CategoryClient{config: c.config}).QueryTool(c)
}

// QueryImplement queries the "implement" edge of the Category entity.
func (c *Category) QueryImplement() *ImplementQuery {
	return (&CategoryClient{config: c.config}).QueryImplement(c)
}

// QueryEquipment queries the "equipment" edge of the Category entity.
func (c *Category) QueryEquipment() *EquipmentQuery {
	return (&CategoryClient{config: c.config}).QueryEquipment(c)
}

// QueryLocation queries the "location" edge of the Category entity.
func (c *Category) QueryLocation() *LocationQuery {
	return (&CategoryClient{config: c.config}).QueryLocation(c)
}

// Update returns a builder for updating this Category.
// Note that you need to call Category.Unwrap() before calling this method if this Category
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Category) Update() *CategoryUpdateOne {
	return (&CategoryClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Category entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Category) Unwrap() *Category {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Category is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Category) String() string {
	var builder strings.Builder
	builder.WriteString("Category(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(c.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(c.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(c.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Categories is a parsable slice of Category.
type Categories []*Category

func (c Categories) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
