// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (e *EquipmentQuery) CollectFields(ctx context.Context, satisfies ...string) *EquipmentQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		e = e.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return e
}

func (e *EquipmentQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *EquipmentQuery {
	return e
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (v *VehicleQuery) CollectFields(ctx context.Context, satisfies ...string) *VehicleQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		v = v.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return v
}

func (v *VehicleQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *VehicleQuery {
	return v
}
