// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/open-farms/inventory/ent/category"
	"github.com/open-farms/inventory/ent/implement"
	"github.com/open-farms/inventory/ent/location"
)

// Implement is the model entity for the Implement schema.
type Implement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImplementQuery when eager-loading is set.
	Edges              ImplementEdges `json:"edges"`
	category_implement *int
	location_implement *int
}

// ImplementEdges holds the relations/edges for other nodes in the graph.
type ImplementEdges struct {
	// Location holds the value of the location edge.
	Location *Location `json:"location,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImplementEdges) LocationOrErr() (*Location, error) {
	if e.loadedTypes[0] {
		if e.Location == nil {
			// The edge location was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: location.Label}
		}
		return e.Location, nil
	}
	return nil, &NotLoadedError{edge: "location"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImplementEdges) CategoryOrErr() (*Category, error) {
	if e.loadedTypes[1] {
		if e.Category == nil {
			// The edge category was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: category.Label}
		}
		return e.Category, nil
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Implement) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case implement.FieldID:
			values[i] = new(sql.NullInt64)
		case implement.FieldName:
			values[i] = new(sql.NullString)
		case implement.FieldCreateTime, implement.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case implement.ForeignKeys[0]: // category_implement
			values[i] = new(sql.NullInt64)
		case implement.ForeignKeys[1]: // location_implement
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Implement", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Implement fields.
func (i *Implement) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case implement.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case implement.FieldCreateTime:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[j])
			} else if value.Valid {
				i.CreateTime = value.Time
			}
		case implement.FieldUpdateTime:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[j])
			} else if value.Valid {
				i.UpdateTime = value.Time
			}
		case implement.FieldName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[j])
			} else if value.Valid {
				i.Name = value.String
			}
		case implement.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field category_implement", value)
			} else if value.Valid {
				i.category_implement = new(int)
				*i.category_implement = int(value.Int64)
			}
		case implement.ForeignKeys[1]:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field location_implement", value)
			} else if value.Valid {
				i.location_implement = new(int)
				*i.location_implement = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryLocation queries the "location" edge of the Implement entity.
func (i *Implement) QueryLocation() *LocationQuery {
	return (&ImplementClient{config: i.config}).QueryLocation(i)
}

// QueryCategory queries the "category" edge of the Implement entity.
func (i *Implement) QueryCategory() *CategoryQuery {
	return (&ImplementClient{config: i.config}).QueryCategory(i)
}

// Update returns a builder for updating this Implement.
// Note that you need to call Implement.Unwrap() before calling this method if this Implement
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Implement) Update() *ImplementUpdateOne {
	return (&ImplementClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the Implement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Implement) Unwrap() *Implement {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Implement is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Implement) String() string {
	var builder strings.Builder
	builder.WriteString("Implement(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(i.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(i.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(i.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Implements is a parsable slice of Implement.
type Implements []*Implement

func (i Implements) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
