// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-farms/inventory/ent/category"
	"github.com/open-farms/inventory/ent/equipment"
	"github.com/open-farms/inventory/ent/implement"
	"github.com/open-farms/inventory/ent/location"
	"github.com/open-farms/inventory/ent/predicate"
	"github.com/open-farms/inventory/ent/tool"
	"github.com/open-farms/inventory/ent/vehicle"
)

// LocationUpdate is the builder for updating Location entities.
type LocationUpdate struct {
	config
	hooks    []Hook
	mutation *LocationMutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (lu *LocationUpdate) Where(ps ...predicate.Location) *LocationUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetCreateTime sets the "create_time" field.
func (lu *LocationUpdate) SetCreateTime(t time.Time) *LocationUpdate {
	lu.mutation.SetCreateTime(t)
	return lu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (lu *LocationUpdate) SetNillableCreateTime(t *time.Time) *LocationUpdate {
	if t != nil {
		lu.SetCreateTime(*t)
	}
	return lu
}

// SetUpdateTime sets the "update_time" field.
func (lu *LocationUpdate) SetUpdateTime(t time.Time) *LocationUpdate {
	lu.mutation.SetUpdateTime(t)
	return lu
}

// SetName sets the "name" field.
func (lu *LocationUpdate) SetName(s string) *LocationUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetZone sets the "zone" field.
func (lu *LocationUpdate) SetZone(i int32) *LocationUpdate {
	lu.mutation.ResetZone()
	lu.mutation.SetZone(i)
	return lu
}

// AddZone adds i to the "zone" field.
func (lu *LocationUpdate) AddZone(i int32) *LocationUpdate {
	lu.mutation.AddZone(i)
	return lu
}

// AddVehicleIDs adds the "vehicle" edge to the Vehicle entity by IDs.
func (lu *LocationUpdate) AddVehicleIDs(ids ...int) *LocationUpdate {
	lu.mutation.AddVehicleIDs(ids...)
	return lu
}

// AddVehicle adds the "vehicle" edges to the Vehicle entity.
func (lu *LocationUpdate) AddVehicle(v ...*Vehicle) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return lu.AddVehicleIDs(ids...)
}

// AddToolIDs adds the "tool" edge to the Tool entity by IDs.
func (lu *LocationUpdate) AddToolIDs(ids ...int) *LocationUpdate {
	lu.mutation.AddToolIDs(ids...)
	return lu
}

// AddTool adds the "tool" edges to the Tool entity.
func (lu *LocationUpdate) AddTool(t ...*Tool) *LocationUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return lu.AddToolIDs(ids...)
}

// AddImplementIDs adds the "implement" edge to the Implement entity by IDs.
func (lu *LocationUpdate) AddImplementIDs(ids ...int) *LocationUpdate {
	lu.mutation.AddImplementIDs(ids...)
	return lu
}

// AddImplement adds the "implement" edges to the Implement entity.
func (lu *LocationUpdate) AddImplement(i ...*Implement) *LocationUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return lu.AddImplementIDs(ids...)
}

// AddEquipmentIDs adds the "equipment" edge to the Equipment entity by IDs.
func (lu *LocationUpdate) AddEquipmentIDs(ids ...int) *LocationUpdate {
	lu.mutation.AddEquipmentIDs(ids...)
	return lu
}

// AddEquipment adds the "equipment" edges to the Equipment entity.
func (lu *LocationUpdate) AddEquipment(e ...*Equipment) *LocationUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return lu.AddEquipmentIDs(ids...)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (lu *LocationUpdate) SetCategoryID(id int) *LocationUpdate {
	lu.mutation.SetCategoryID(id)
	return lu
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (lu *LocationUpdate) SetNillableCategoryID(id *int) *LocationUpdate {
	if id != nil {
		lu = lu.SetCategoryID(*id)
	}
	return lu
}

// SetCategory sets the "category" edge to the Category entity.
func (lu *LocationUpdate) SetCategory(c *Category) *LocationUpdate {
	return lu.SetCategoryID(c.ID)
}

// Mutation returns the LocationMutation object of the builder.
func (lu *LocationUpdate) Mutation() *LocationMutation {
	return lu.mutation
}

// ClearVehicle clears all "vehicle" edges to the Vehicle entity.
func (lu *LocationUpdate) ClearVehicle() *LocationUpdate {
	lu.mutation.ClearVehicle()
	return lu
}

// RemoveVehicleIDs removes the "vehicle" edge to Vehicle entities by IDs.
func (lu *LocationUpdate) RemoveVehicleIDs(ids ...int) *LocationUpdate {
	lu.mutation.RemoveVehicleIDs(ids...)
	return lu
}

// RemoveVehicle removes "vehicle" edges to Vehicle entities.
func (lu *LocationUpdate) RemoveVehicle(v ...*Vehicle) *LocationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return lu.RemoveVehicleIDs(ids...)
}

// ClearTool clears all "tool" edges to the Tool entity.
func (lu *LocationUpdate) ClearTool() *LocationUpdate {
	lu.mutation.ClearTool()
	return lu
}

// RemoveToolIDs removes the "tool" edge to Tool entities by IDs.
func (lu *LocationUpdate) RemoveToolIDs(ids ...int) *LocationUpdate {
	lu.mutation.RemoveToolIDs(ids...)
	return lu
}

// RemoveTool removes "tool" edges to Tool entities.
func (lu *LocationUpdate) RemoveTool(t ...*Tool) *LocationUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return lu.RemoveToolIDs(ids...)
}

// ClearImplement clears all "implement" edges to the Implement entity.
func (lu *LocationUpdate) ClearImplement() *LocationUpdate {
	lu.mutation.ClearImplement()
	return lu
}

// RemoveImplementIDs removes the "implement" edge to Implement entities by IDs.
func (lu *LocationUpdate) RemoveImplementIDs(ids ...int) *LocationUpdate {
	lu.mutation.RemoveImplementIDs(ids...)
	return lu
}

// RemoveImplement removes "implement" edges to Implement entities.
func (lu *LocationUpdate) RemoveImplement(i ...*Implement) *LocationUpdate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return lu.RemoveImplementIDs(ids...)
}

// ClearEquipment clears all "equipment" edges to the Equipment entity.
func (lu *LocationUpdate) ClearEquipment() *LocationUpdate {
	lu.mutation.ClearEquipment()
	return lu
}

// RemoveEquipmentIDs removes the "equipment" edge to Equipment entities by IDs.
func (lu *LocationUpdate) RemoveEquipmentIDs(ids ...int) *LocationUpdate {
	lu.mutation.RemoveEquipmentIDs(ids...)
	return lu
}

// RemoveEquipment removes "equipment" edges to Equipment entities.
func (lu *LocationUpdate) RemoveEquipment(e ...*Equipment) *LocationUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return lu.RemoveEquipmentIDs(ids...)
}

// ClearCategory clears the "category" edge to the Category entity.
func (lu *LocationUpdate) ClearCategory() *LocationUpdate {
	lu.mutation.ClearCategory()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LocationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	lu.defaults()
	if len(lu.hooks) == 0 {
		affected, err = lu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lu.mutation = mutation
			affected, err = lu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lu.hooks) - 1; i >= 0; i-- {
			if lu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LocationUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LocationUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LocationUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lu *LocationUpdate) defaults() {
	if _, ok := lu.mutation.UpdateTime(); !ok {
		v := location.UpdateDefaultUpdateTime()
		lu.mutation.SetUpdateTime(v)
	}
}

func (lu *LocationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   location.Table,
			Columns: location.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: location.FieldID,
			},
		},
	}
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: location.FieldCreateTime,
		})
	}
	if value, ok := lu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: location.FieldUpdateTime,
		})
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: location.FieldName,
		})
	}
	if value, ok := lu.mutation.Zone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: location.FieldZone,
		})
	}
	if value, ok := lu.mutation.AddedZone(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: location.FieldZone,
		})
	}
	if lu.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedVehicleIDs(); len(nodes) > 0 && !lu.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.ToolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedToolIDs(); len(nodes) > 0 && !lu.mutation.ToolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.ToolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.ImplementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedImplementIDs(); len(nodes) > 0 && !lu.mutation.ImplementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.ImplementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedEquipmentIDs(); len(nodes) > 0 && !lu.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.CategoryTable,
			Columns: []string{location.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.CategoryTable,
			Columns: []string{location.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// LocationUpdateOne is the builder for updating a single Location entity.
type LocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationMutation
}

// SetCreateTime sets the "create_time" field.
func (luo *LocationUpdateOne) SetCreateTime(t time.Time) *LocationUpdateOne {
	luo.mutation.SetCreateTime(t)
	return luo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (luo *LocationUpdateOne) SetNillableCreateTime(t *time.Time) *LocationUpdateOne {
	if t != nil {
		luo.SetCreateTime(*t)
	}
	return luo
}

// SetUpdateTime sets the "update_time" field.
func (luo *LocationUpdateOne) SetUpdateTime(t time.Time) *LocationUpdateOne {
	luo.mutation.SetUpdateTime(t)
	return luo
}

// SetName sets the "name" field.
func (luo *LocationUpdateOne) SetName(s string) *LocationUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetZone sets the "zone" field.
func (luo *LocationUpdateOne) SetZone(i int32) *LocationUpdateOne {
	luo.mutation.ResetZone()
	luo.mutation.SetZone(i)
	return luo
}

// AddZone adds i to the "zone" field.
func (luo *LocationUpdateOne) AddZone(i int32) *LocationUpdateOne {
	luo.mutation.AddZone(i)
	return luo
}

// AddVehicleIDs adds the "vehicle" edge to the Vehicle entity by IDs.
func (luo *LocationUpdateOne) AddVehicleIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.AddVehicleIDs(ids...)
	return luo
}

// AddVehicle adds the "vehicle" edges to the Vehicle entity.
func (luo *LocationUpdateOne) AddVehicle(v ...*Vehicle) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return luo.AddVehicleIDs(ids...)
}

// AddToolIDs adds the "tool" edge to the Tool entity by IDs.
func (luo *LocationUpdateOne) AddToolIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.AddToolIDs(ids...)
	return luo
}

// AddTool adds the "tool" edges to the Tool entity.
func (luo *LocationUpdateOne) AddTool(t ...*Tool) *LocationUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return luo.AddToolIDs(ids...)
}

// AddImplementIDs adds the "implement" edge to the Implement entity by IDs.
func (luo *LocationUpdateOne) AddImplementIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.AddImplementIDs(ids...)
	return luo
}

// AddImplement adds the "implement" edges to the Implement entity.
func (luo *LocationUpdateOne) AddImplement(i ...*Implement) *LocationUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return luo.AddImplementIDs(ids...)
}

// AddEquipmentIDs adds the "equipment" edge to the Equipment entity by IDs.
func (luo *LocationUpdateOne) AddEquipmentIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.AddEquipmentIDs(ids...)
	return luo
}

// AddEquipment adds the "equipment" edges to the Equipment entity.
func (luo *LocationUpdateOne) AddEquipment(e ...*Equipment) *LocationUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return luo.AddEquipmentIDs(ids...)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (luo *LocationUpdateOne) SetCategoryID(id int) *LocationUpdateOne {
	luo.mutation.SetCategoryID(id)
	return luo
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (luo *LocationUpdateOne) SetNillableCategoryID(id *int) *LocationUpdateOne {
	if id != nil {
		luo = luo.SetCategoryID(*id)
	}
	return luo
}

// SetCategory sets the "category" edge to the Category entity.
func (luo *LocationUpdateOne) SetCategory(c *Category) *LocationUpdateOne {
	return luo.SetCategoryID(c.ID)
}

// Mutation returns the LocationMutation object of the builder.
func (luo *LocationUpdateOne) Mutation() *LocationMutation {
	return luo.mutation
}

// ClearVehicle clears all "vehicle" edges to the Vehicle entity.
func (luo *LocationUpdateOne) ClearVehicle() *LocationUpdateOne {
	luo.mutation.ClearVehicle()
	return luo
}

// RemoveVehicleIDs removes the "vehicle" edge to Vehicle entities by IDs.
func (luo *LocationUpdateOne) RemoveVehicleIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.RemoveVehicleIDs(ids...)
	return luo
}

// RemoveVehicle removes "vehicle" edges to Vehicle entities.
func (luo *LocationUpdateOne) RemoveVehicle(v ...*Vehicle) *LocationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return luo.RemoveVehicleIDs(ids...)
}

// ClearTool clears all "tool" edges to the Tool entity.
func (luo *LocationUpdateOne) ClearTool() *LocationUpdateOne {
	luo.mutation.ClearTool()
	return luo
}

// RemoveToolIDs removes the "tool" edge to Tool entities by IDs.
func (luo *LocationUpdateOne) RemoveToolIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.RemoveToolIDs(ids...)
	return luo
}

// RemoveTool removes "tool" edges to Tool entities.
func (luo *LocationUpdateOne) RemoveTool(t ...*Tool) *LocationUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return luo.RemoveToolIDs(ids...)
}

// ClearImplement clears all "implement" edges to the Implement entity.
func (luo *LocationUpdateOne) ClearImplement() *LocationUpdateOne {
	luo.mutation.ClearImplement()
	return luo
}

// RemoveImplementIDs removes the "implement" edge to Implement entities by IDs.
func (luo *LocationUpdateOne) RemoveImplementIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.RemoveImplementIDs(ids...)
	return luo
}

// RemoveImplement removes "implement" edges to Implement entities.
func (luo *LocationUpdateOne) RemoveImplement(i ...*Implement) *LocationUpdateOne {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return luo.RemoveImplementIDs(ids...)
}

// ClearEquipment clears all "equipment" edges to the Equipment entity.
func (luo *LocationUpdateOne) ClearEquipment() *LocationUpdateOne {
	luo.mutation.ClearEquipment()
	return luo
}

// RemoveEquipmentIDs removes the "equipment" edge to Equipment entities by IDs.
func (luo *LocationUpdateOne) RemoveEquipmentIDs(ids ...int) *LocationUpdateOne {
	luo.mutation.RemoveEquipmentIDs(ids...)
	return luo
}

// RemoveEquipment removes "equipment" edges to Equipment entities.
func (luo *LocationUpdateOne) RemoveEquipment(e ...*Equipment) *LocationUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return luo.RemoveEquipmentIDs(ids...)
}

// ClearCategory clears the "category" edge to the Category entity.
func (luo *LocationUpdateOne) ClearCategory() *LocationUpdateOne {
	luo.mutation.ClearCategory()
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LocationUpdateOne) Select(field string, fields ...string) *LocationUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Location entity.
func (luo *LocationUpdateOne) Save(ctx context.Context) (*Location, error) {
	var (
		err  error
		node *Location
	)
	luo.defaults()
	if len(luo.hooks) == 0 {
		node, err = luo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			luo.mutation = mutation
			node, err = luo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luo.hooks) - 1; i >= 0; i-- {
			if luo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LocationUpdateOne) SaveX(ctx context.Context) *Location {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LocationUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LocationUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (luo *LocationUpdateOne) defaults() {
	if _, ok := luo.mutation.UpdateTime(); !ok {
		v := location.UpdateDefaultUpdateTime()
		luo.mutation.SetUpdateTime(v)
	}
}

func (luo *LocationUpdateOne) sqlSave(ctx context.Context) (_node *Location, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   location.Table,
			Columns: location.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: location.FieldID,
			},
		},
	}
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Location.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, location.FieldID)
		for _, f := range fields {
			if !location.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != location.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: location.FieldCreateTime,
		})
	}
	if value, ok := luo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: location.FieldUpdateTime,
		})
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: location.FieldName,
		})
	}
	if value, ok := luo.mutation.Zone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: location.FieldZone,
		})
	}
	if value, ok := luo.mutation.AddedZone(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: location.FieldZone,
		})
	}
	if luo.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedVehicleIDs(); len(nodes) > 0 && !luo.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.VehicleTable,
			Columns: []string{location.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vehicle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.ToolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedToolIDs(); len(nodes) > 0 && !luo.mutation.ToolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.ToolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ToolTable,
			Columns: []string{location.ToolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tool.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.ImplementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedImplementIDs(); len(nodes) > 0 && !luo.mutation.ImplementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.ImplementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.ImplementTable,
			Columns: []string{location.ImplementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: implement.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedEquipmentIDs(); len(nodes) > 0 && !luo.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.EquipmentTable,
			Columns: []string{location.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.CategoryTable,
			Columns: []string{location.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.CategoryTable,
			Columns: []string{location.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: category.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Location{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
