// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Implement is the predicate function for implement builders.
type Implement func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// Vehicle is the predicate function for vehicle builders.
type Vehicle func(*sql.Selector)
